config/routes.rb
Houtai::Application.routes.draw do
  resources :links

  resources :videos

  resources :articles

  resources :notices

  resources :periodicals

  match '/downloads/kind/:kind', to: 'downloads#show_kind', :as => 'downloads_kind'

  resources :downloads

  resources :albums do
    resources :photos
  end

  match '/aboutshetuans/kind/:kind', to: 'aboutshetuans#show_kind', :as => 'aboutshetuans_kind'

  match '/aboutshetuans/star', to: 'aboutshetuans#star'

  resources :aboutshetuans

  resources :stars

  match '/aboutshelians/theme/:theme', to: 'aboutshelians#theme', :as => 'aboutshelians_theme'

  match '/aboutshelians/star', to: 'aboutshelians#star'

  resources :aboutshelians

  mount Rich::Engine => '/rich', :as => 'rich'
  
  match '/events/area/:area', to: 'events#show_area', :as => 'events_area'

  match '/events/kind/:kind', to: 'events#show_kind', :as => 'events_kind'

  resources :events

  root :to => 'home#index'

  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'
  
  devise_for :admins

end

app/models/aboutshelian.rb
#coding: utf-8
class Aboutshelian < ActiveRecord::Base
	attr_accessible :title, :content

	validates_presence_of :title, :content

	def title_enum
		['社联章程','社联骨干','工作流程','主席团','秘书处','督导处','外联部','内务部','宣传部','策划部','新闻部']
	end

end

app/models/aboutshetuan.rb
#coding: utf-8
class Aboutshetuan < ActiveRecord::Base
	attr_accessible :name, :president, :contact, :kind, :institute, :begin, :is_excellent, :detail, :logo
	
	validates_presence_of :name, :president, :kind, :begin
	validates_uniqueness_of :name
	# has_many :attachments, :as => :attachmentable, :dependent => :destroy

  mount_uploader :logo, AttachmentUploader

	def kind_enum
		['社会公益类','体育运动类','文艺特长类','学术创新类','应用实践类']
	end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/album.rb
class Album < ActiveRecord::Base
	attr_accessible :name, :description
	
	has_many :photos, :dependent => :destroy
	
	validates_presence_of :name
	
	validates_uniqueness_of :name

  paginates_per 12

	default_scope order: 'albums.created_at DESC'

	def at_least_one_photo?
		delf.photos.present?
	end
end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :title, :author, :unit, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'articles.created_at DESC'
end

app/models/download.rb
#coding: utf-8
class Download < ActiveRecord::Base
	attr_accessible :description, :kind, :attachment
	
	validates_presence_of :description, :kind, :attachment
	validates_uniqueness_of :attachment

  mount_uploader :attachment, AttachmentUploader

	def kind_enum
		['成立社团相关','社团事务相关','场地借用相关']
	end
end

app/models/event.rb
#coding: utf-8
class Event < ActiveRecord::Base
	attr_accessible :title, :kind, :photo, :begin, :end, :address, :organizer, :sponsor, :area, :views_count, :contact, :is_index, :content
	
	validates_presence_of :title, :kind, :begin, :end, :address, :organizer, :content, :area

  mount_uploader :photo, AttachmentUploader
	
	acts_as_views_count :delay => 1
	# default_scope order: 'events.created_at DESC'
	
	def kind_enum
		['讲座沙龙','校园文化','竞赛创新','实践公益','其他']
	end
	def area_enum
		['社联活动','校园活动']
	end
end

app/models/link.rb
class Link < ActiveRecord::Base
	attr_accessible :name, :address
	validates_presence_of :name, :address
	validates_uniqueness_of :name, :address
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	attr_accessible :title, :from, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'notices.created_at DESC'
end

app/models/periodical.rb
class Periodical < ActiveRecord::Base
	attr_accessible :name, :author, :unit, :content, :views_count
	
	validates_presence_of :name, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'periodicals.created_at DESC'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessible :photo_file, :album_id, :description

	validates_presence_of :album_id, :photo_file

  belongs_to :album
  
  mount_uploader :photo_file, AttachmentUploader

  paginates_per 35
end

app/models/star.rb
#coding: utf-8
class Star < ActiveRecord::Base
	attr_accessible :name, :photo, :department, :position, :contact, :institute, :motto, :detail, :area
	
	validates_presence_of :name, :department, :area
	validates_uniqueness_of :name

  mount_uploader :photo, AttachmentUploader
  
  paginates_per 1

	def area_enum
		['社联之星','社团之星']
	end
end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :name, :video_id, :screenshot, :views_count
  
	validates_presence_of :name, :video_id, :screenshot

  mount_uploader :screenshot, AttachmentUploader
	
	acts_as_views_count :delay => 1

	default_scope order: 'videos.created_at DESC'

  paginates_per 12
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.order("created_at desc").page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])
    @notice.update_views_count
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @notice = Notice.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(params[:notice])

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render json: @notice, status: :created, location: @notice }
      else
        format.html { render action: "new" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @notice = Notice.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def no_album?
      !Album.first
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :标题 %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :来源 %><br />
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :正文 %><br />
    <%= f.kindeditor :content %>
  </div>
  <div class="actions">
    <%= f.submit "发布"%>
  </div>
<% end %>

app/views/notices/_head_body.html.erb
<div class="head_body">
  <p class="main_title">
    新闻中心
  </p>
  <div class="web_map">
    <%= link_to "首页", root_path %>
    <span class="map_go">>></span>
    <%= link_to "新闻中心", notices_path %>
    <span class="map_go">>></span>
    <% if params[:controller] == 'notices' and params[:action] == 'index' %>
      <%= link_to "通知公告", notices_path %>
        <% if admin_signed_in? %>
          (<span class="load"><%= link_to '发布通知', new_notice_path %></span>)
        <% end %>
    <% elsif params[:controller] == 'notices' and params[:action] == 'show' %>
      <%= link_to "通知公告", notices_path %>
      <span class="map_go">>></span>
      <%= @notice.title %>
        <% if admin_signed_in? %>
          (<span class="load"><%= link_to '修改', edit_notice_path %></span>)
        <% end %>
    <% end %>
  </div>
</div>

app/views/notices/edit.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<div id="body">
  <div class="inner_body">
		<%= link_to '返回', :back %>
		<%= link_to '查看', @notice %>

		<h2>修改"<%= @notice.title %>"</h2>

		<%= render 'form' %>

  </div>
</div>

app/views/notices/index.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "news_center", :media => "all" %>
<% provide :title, "新闻中心 | 通知公告" %>
<div id="body">
  <div class="inner_body">
    <%= render 'head_body' %>
    <div class="left_body">
      <ul class="news_list">
        <% @notices.each do |notice| %>
        <li>
          <p class="the_title">
            <%= link_to notice.title, notice %>
          </p>
          <div class="the_text">
            <%= raw notice.content[0..140] %><%= '...' if notice.content.size >140 %>
          </div>
          <span class="counter"><%= link_to "阅读", notice %>（<%= notice.views_count_s %>）</span>
          <div class="Clear"></div>
        </li>
        <% end %>
        <div class="page_box">
          <%= paginate @notices %>
        </div>
      </ul>
    </div>
    <%= render 'shares/right_body' %>
    <div class="Clear"></div>
  </div>
</div>

app/views/notices/new.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<div id="body">
  <div class="inner_body">
		<%= link_to '返回', notices_path %>

		<h2>发布通知</h2>

		<%= render 'form' %>

  </div>
</div>

app/views/notices/show.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "news_more", :media => "all" %>
<% provide :title, "新闻中心 | 通知公告 | "+@notice.title %>
<div id="body">
  <div class="inner_body">
    <%= render 'head_body' %>
    <div class="left_body">
      <div class="content">
        <div class="article_title">
          <%= @notice.title %>
        </div>
        <div class="article_info">
          <span class="info_left">
            <span class="from">
              来自：<%= @notice.from %>
            </span>
          </span>
          <span class="info_right">
            <%= @notice.created_at.strftime("%Y年%m月%d日 %H:%M") %> 阅读：<%= @notice.views_count_s %>
          </span>
          <div class="Clear"></div>
        </div>
        <div class="article_text">
          <%= raw @notice.content %>
        </div>
        <div class="Clear"></div><!-- 清除上面div浮动 -->
        <%= render 'shares/baidu_share' %>
      </div>
    </div>
    <%= render 'shares/right_body' %>
    <div class="Clear"></div>
  </div>
</div>