config/routes.rb
Houtai::Application.routes.draw do
  resources :links

  resources :videos

  resources :articles

  resources :notices

  resources :periodicals

  match '/downloads/kind/:kind', to: 'downloads#show_kind', :as => 'downloads_kind'

  resources :downloads

  resources :albums do
    resources :photos
  end

  match '/aboutshetuans/kind/:kind', to: 'aboutshetuans#show_kind', :as => 'aboutshetuans_kind'

  match '/aboutshetuans/star', to: 'aboutshetuans#star'

  resources :aboutshetuans

  resources :stars

  match '/aboutshelians/theme/:theme', to: 'aboutshelians#theme', :as => 'aboutshelians_theme'

  match '/aboutshelians/star', to: 'aboutshelians#star'

  resources :aboutshelians

  mount Rich::Engine => '/rich', :as => 'rich'
  
  match '/events/area/:area', to: 'events#show_area', :as => 'events_area'

  match '/events/kind/:kind', to: 'events#show_kind', :as => 'events_kind'

  resources :events

  root :to => 'home#index'

  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'
  
  devise_for :admins

end

app/models/aboutshelian.rb
#coding: utf-8
class Aboutshelian < ActiveRecord::Base
	attr_accessible :title, :content

	validates_presence_of :title, :content

	def title_enum
		['社联章程','社联骨干','工作流程','主席团','秘书处','督导处','外联部','内务部','宣传部','策划部','新闻部']
	end

end

app/models/aboutshetuan.rb
#coding: utf-8
class Aboutshetuan < ActiveRecord::Base
	attr_accessible :name, :president, :contact, :kind, :institute, :begin, :is_excellent, :detail, :logo
	
	validates_presence_of :name, :president, :kind, :begin
	validates_uniqueness_of :name
	# has_many :attachments, :as => :attachmentable, :dependent => :destroy

  mount_uploader :logo, AttachmentUploader

	def kind_enum
		['社会公益类','体育运动类','文艺特长类','学术创新类','应用实践类']
	end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/album.rb
class Album < ActiveRecord::Base
	attr_accessible :name, :description
	
	has_many :photos, :dependent => :destroy
	
	validates_presence_of :name
	
	validates_uniqueness_of :name

  paginates_per 12

	default_scope order: 'albums.created_at DESC'

	def at_least_one_photo?
		delf.photos.present?
	end
end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :title, :author, :unit, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'articles.created_at DESC'
end

app/models/download.rb
#coding: utf-8
class Download < ActiveRecord::Base
	attr_accessible :description, :kind, :attachment
	
	validates_presence_of :description, :kind, :attachment
	validates_uniqueness_of :attachment

  mount_uploader :attachment, AttachmentUploader

	def kind_enum
		['成立社团相关','社团事务相关','场地借用相关']
	end
end

app/models/event.rb
#coding: utf-8
class Event < ActiveRecord::Base
	attr_accessible :title, :kind, :photo, :begin, :end, :address, :organizer, :sponsor, :area, :views_count, :contact, :is_index, :content
	
	validates_presence_of :title, :kind, :begin, :end, :address, :organizer, :content, :area

  mount_uploader :photo, AttachmentUploader
	
	acts_as_views_count :delay => 1
	# default_scope order: 'events.created_at DESC'
	
	def kind_enum
		['讲座沙龙','校园文化','竞赛创新','实践公益','其他']
	end
	def area_enum
		['社联活动','校园活动']
	end
end

app/models/link.rb
class Link < ActiveRecord::Base
	attr_accessible :name, :address
	validates_presence_of :name, :address
	validates_uniqueness_of :name, :address
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	attr_accessible :title, :from, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'notices.created_at DESC'
end

app/models/periodical.rb
class Periodical < ActiveRecord::Base
	attr_accessible :name, :author, :unit, :content, :views_count
	
	validates_presence_of :name, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'periodicals.created_at DESC'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessible :photo_file, :album_id, :description

	validates_presence_of :album_id, :photo_file

  belongs_to :album
  
  mount_uploader :photo_file, AttachmentUploader

  paginates_per 35
end

app/models/star.rb
#coding: utf-8
class Star < ActiveRecord::Base
	attr_accessible :name, :photo, :department, :position, :contact, :institute, :motto, :detail, :area
	
	validates_presence_of :name, :department, :area
	validates_uniqueness_of :name

  mount_uploader :photo, AttachmentUploader
  
  paginates_per 1

	def area_enum
		['社联之星','社团之星']
	end
end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :name, :video_id, :screenshot, :views_count
  
	validates_presence_of :name, :video_id, :screenshot

  mount_uploader :screenshot, AttachmentUploader
	
	acts_as_views_count :delay => 1

	default_scope order: 'videos.created_at DESC'

  paginates_per 12
end

app/controllers/home_controller.rb
#coding: utf-8
class HomeController < ApplicationController
  def index
    @album = Album.first
  	@events = Event.order("created_at desc").where(:is_index => "1").limit(3)
  	@articles = Article.order("created_at desc").limit(5)
    @notices = Notice.order("created_at desc").limit(5)
    @periodicals = Periodical.order("created_at desc").limit(5)
    @events_shelian = Event.order("created_at desc").limit(5).where(:area => '社联活动')
    @events_xiaoyuan = Event.order("created_at desc").limit(5).where(:area => '校园活动')
    @video = Video.last
    @photos = Photo.order("created_at desc").limit(10)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def no_album?
      !Album.first
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag  "home_page_style", :media => "all" %>
<%= javascript_include_tag "home_page_app" %>
<% provide :title, "首页" %>
<div id="body">
  <div class="inner_body">
    <div class="main_pic_show">
      <%= image_tag @album.photos.last.photo_file, :width => "960px", :height => "300px" if @album and @album.photos.exists? %>
    </div>
    <div class="content">
      <div class="pic_content_box">
        <div class="left">
          <div class="right">
            <div class="center">
              <div class="see_pic_por">
                <div class="show_portal">
                <% if @events.exists? %>
                  <%= link_to image_tag(@events.first.photo.url(:index_big), :id => "show", :alt => "pic", :width => "560px", :height => "400px"), @events.first, :id => "main_pic_link" %>
                  <div class="pic_info">
                    <div class="pic_info_bg"></div>
                    <div class="pic_info_content">
                      <%= link_to @events.first.title, @events_shelian.first, :id => "main_link" %>
                    </div>
                  </div>
                </div>
                <div class="pic_row">
                  <%= image_tag "row.jpg", :alt => "row", :id => "left_row", :style => "margin-top:30px;" %>
                </div>
                <div class="pic_menu">
                  <ul>
                    <% i = 1 %>
                    <% @events.each do |event| %>
                    <li>
                      <img src="<%= event.photo.url(:index_small) %>" target_src="<%= event.photo.url(:index_big) %>" js_num="<%= i %>" alt="pic" />
                      <div class="pic_info">
                        <div class="pic_info_bg"></div>
                        <div class="pic_info_content">
                          <%= link_to event.title, event %>
                        </div>
                      </div>
                    </li>
                    <% i = i+1 %>
                    <% end %>
                  </ul>
                <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="text_content_box">
        <ul class="text_news_box_list">
          <li>
            <div class="small_box">
              <div class="s_box_left">
                <div class="s_box_right">
                  <div class="s_box_center">
                    <div class="box_title">
                      <span class="the_title normal_font">
                        <%= link_to "社联新闻", articles_path %>
                      </span>
                    </div>
                    <div class="the_content">
                      <ul>
                        <% @articles.each do |article| %>
                        <li>
                          <%= link_to article.title[0..13], article, :title => article.title %><%= '...' if article.title.size >14 %>
                          <span class="date"><%= article.created_at.strftime("%m月%d日") %></span>
                        </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="small_box">
              <div class="s_box_left">
                <div class="s_box_right">
                  <div class="s_box_center">
                    <div class="box_title">
                      <span class="the_title normal_font">
                        <%= link_to "通知公告", notices_path %>
                      </span>
                    </div>
                    <div class="the_content">
                      <ul>
                        <% @notices.each do |notice| %>
                        <li>
                          <%= link_to notice.title[0..13], notice, :title => notice.title %><%= '...' if notice.title.size >14 %>
                          <span class="date"><%= notice.created_at.strftime("%m月%d日") %></span>
                        </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li style="margin-right:0;">
            <div class="small_box">
              <div class="s_box_left">
                <div class="s_box_right">
                  <div class="s_box_center">
                    <div class="box_title">
                      <span class="the_title normal_font">
                        <%= link_to "社团新闻", periodicals_path %>
                      </span>
                    </div>
                    <div class="the_content">
                      <ul>
                        <% @periodicals.each do |periodical| %>
                        <li>
                          <%= link_to periodical.name[0..13], periodical, :title => periodical.name %><%= '...' if periodical.name.size >14 %>
                          <span class="date"><%= periodical.created_at.strftime("%m月%d日") %></span>
                        </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
        <div class="Clear"></div>
        <ul class="text_news_box_list">
          <li>
            <div class="small_box">
              <div class="s_box_left">
                <div class="s_box_right">
                  <div class="s_box_center">
                    <div class="box_title">
                      <span class="the_title normal_font">
                        <%= link_to "社联活动", events_path %>
                      </span>
                    </div>
                    <div class="the_content">
                      <ul>
                        <% @events_shelian.each do |event| %>
                        <li>
                          [<%= event.kind %>]<%= link_to event.title[0..9], event, :title => event.title %><%= '...' if event.title.size >10 %>
                          <span class="date"><%= event.created_at.strftime("%m月%d日") %></span>
                        </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="small_box">
              <div class="s_box_left">
                <div class="s_box_right">
                  <div class="s_box_center">
                    <div class="box_title">
                      <span class="the_title normal_font">
                        <%= link_to "校园活动", events_path %>
                      </span>
                    </div>
                    <div class="the_content">
                      <ul>
                        <% @events_xiaoyuan.each do |event| %>
                        <li>
                          [<%= event.kind %>]<%= link_to event.title[0..10], event, :title => event.title %><%= '...' if event.title.size >10 %>
                          <span class="date"><%= event.created_at.strftime("%m月%d日") %></span>
                        </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li style="margin-right:0;">
            <div class="small_box">
              <div class="s_box_left">
                <div class="s_box_right">
                  <div class="s_box_center">
                    <div class="box_title">
                      <span class="the_title normal_font">
                        <%= link_to "社联视频", videos_path %>
                      </span>
                    </div>
                    <div class="the_content video_link">
                      <% if @video %>
                      <%= link_to image_tag(@video.screenshot.url(:index_small), :style => "width:240px; height:150px; margin-left: 2px;" ), @video %>
                      <div class="title_bg"></div>
                      <div class="video_title">
                        <%= @video.name[0..17] %><%= '...' if @video.name.size >18 %>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
        <div class="Clear"></div>
      </div>
      <div class="pic_slide_box">
        <div class="m_box_left">
          <div class="m_box_right">
            <div class="m_box_center">
              <div class="slide_content">
                <div class="slide_row">
                  <div class="left_row"></div>
                </div>
                <div class="slide_pic_list">
                  <div class="action_item" style="margin-left:0px;">
                    <ul class="list1">
                      <% @photos.each do |photo| %>
                      <li>
                        <%= link_to image_tag(photo.photo_file.url(:intro)), album_photos_path(photo.album) %>
                      </li>
                      <% end %>
                    </ul>
                    <ul class="list2">
                      <% @photos.each do |photo| %>
                      <li>
                        <%= link_to image_tag(photo.photo_file.url(:intro)), album_photos_path(photo.album) %>
                      </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
                <div class="slide_row">
                  <div class="right_row"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>