config/routes.rb
Houtai::Application.routes.draw do
  resources :links

  resources :videos

  resources :articles

  resources :notices

  resources :periodicals

  match '/downloads/kind/:kind', to: 'downloads#show_kind', :as => 'downloads_kind'

  resources :downloads

  resources :albums do
    resources :photos
  end

  match '/aboutshetuans/kind/:kind', to: 'aboutshetuans#show_kind', :as => 'aboutshetuans_kind'

  match '/aboutshetuans/star', to: 'aboutshetuans#star'

  resources :aboutshetuans

  resources :stars

  match '/aboutshelians/theme/:theme', to: 'aboutshelians#theme', :as => 'aboutshelians_theme'

  match '/aboutshelians/star', to: 'aboutshelians#star'

  resources :aboutshelians

  mount Rich::Engine => '/rich', :as => 'rich'
  
  match '/events/area/:area', to: 'events#show_area', :as => 'events_area'

  match '/events/kind/:kind', to: 'events#show_kind', :as => 'events_kind'

  resources :events

  root :to => 'home#index'

  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'
  
  devise_for :admins

end

app/models/aboutshelian.rb
#coding: utf-8
class Aboutshelian < ActiveRecord::Base
	attr_accessible :title, :content

	validates_presence_of :title, :content

	def title_enum
		['社联章程','社联骨干','工作流程','主席团','秘书处','督导处','外联部','内务部','宣传部','策划部','新闻部']
	end

end

app/models/aboutshetuan.rb
#coding: utf-8
class Aboutshetuan < ActiveRecord::Base
	attr_accessible :name, :president, :contact, :kind, :institute, :begin, :is_excellent, :detail, :logo
	
	validates_presence_of :name, :president, :kind, :begin
	validates_uniqueness_of :name
	# has_many :attachments, :as => :attachmentable, :dependent => :destroy

  mount_uploader :logo, AttachmentUploader

	def kind_enum
		['社会公益类','体育运动类','文艺特长类','学术创新类','应用实践类']
	end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/album.rb
class Album < ActiveRecord::Base
	attr_accessible :name, :description
	
	has_many :photos, :dependent => :destroy
	
	validates_presence_of :name
	
	validates_uniqueness_of :name

  paginates_per 12

	default_scope order: 'albums.created_at DESC'

	def at_least_one_photo?
		delf.photos.present?
	end
end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :title, :author, :unit, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'articles.created_at DESC'
end

app/models/download.rb
#coding: utf-8
class Download < ActiveRecord::Base
	attr_accessible :description, :kind, :attachment
	
	validates_presence_of :description, :kind, :attachment
	validates_uniqueness_of :attachment

  mount_uploader :attachment, AttachmentUploader

	def kind_enum
		['成立社团相关','社团事务相关','场地借用相关']
	end
end

app/models/event.rb
#coding: utf-8
class Event < ActiveRecord::Base
	attr_accessible :title, :kind, :photo, :begin, :end, :address, :organizer, :sponsor, :area, :views_count, :contact, :is_index, :content
	
	validates_presence_of :title, :kind, :begin, :end, :address, :organizer, :content, :area

  mount_uploader :photo, AttachmentUploader
	
	acts_as_views_count :delay => 1
	# default_scope order: 'events.created_at DESC'
	
	def kind_enum
		['讲座沙龙','校园文化','竞赛创新','实践公益','其他']
	end
	def area_enum
		['社联活动','校园活动']
	end
end

app/models/link.rb
class Link < ActiveRecord::Base
	attr_accessible :name, :address
	validates_presence_of :name, :address
	validates_uniqueness_of :name, :address
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	attr_accessible :title, :from, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'notices.created_at DESC'
end

app/models/periodical.rb
class Periodical < ActiveRecord::Base
	attr_accessible :name, :author, :unit, :content, :views_count
	
	validates_presence_of :name, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'periodicals.created_at DESC'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessible :photo_file, :album_id, :description

	validates_presence_of :album_id, :photo_file

  belongs_to :album
  
  mount_uploader :photo_file, AttachmentUploader

  paginates_per 35
end

app/models/star.rb
#coding: utf-8
class Star < ActiveRecord::Base
	attr_accessible :name, :photo, :department, :position, :contact, :institute, :motto, :detail, :area
	
	validates_presence_of :name, :department, :area
	validates_uniqueness_of :name

  mount_uploader :photo, AttachmentUploader
  
  paginates_per 1

	def area_enum
		['社联之星','社团之星']
	end
end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :name, :video_id, :screenshot, :views_count
  
	validates_presence_of :name, :video_id, :screenshot

  mount_uploader :screenshot, AttachmentUploader
	
	acts_as_views_count :delay => 1

	default_scope order: 'videos.created_at DESC'

  paginates_per 12
end

app/controllers/events_controller.rb
#coding: utf-8
class EventsController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  # GET /events
  # GET /events.json
  def index
    @events = Event.order("created_at desc").page params[:page]
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    @event.update_views_count
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  def show_area
    @event_areas =  Event.order("created_at desc").where(:area => params[:area]).page params[:page]
  end

  def show_kind
    @event_kinds =  Event.order("created_at desc").where(:kind => params[:kind]).page params[:page]
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        Attachment.create(:attachment => params[:attachment], :attachmentable => @event) if params[:attachment]
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def no_album?
      !Album.first
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:multipart => true}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :活动宣传照片 %><br />
    <%= f.file_field :photo %><br />
  </div>
  <div class="field">
    <%= f.label :范围 %><br />
    <%= f.select :area, ['社联活动','校园活动'] %>
  </div>
  <div class="field">
    <%= f.label :标题 %><br />
    <%= f.text_field :title %>
  </div>
  <div class="select">
    <%= f.label :类型 %><br />
    <%= f.select :kind, ['讲座沙龙','校园文化','竞赛创新','实践公益','其他'] %>
  </div>
  <div class="field">
    <%= f.label :开始时间 %><br />
    <%= f.datetime_select :begin %>
  </div>
  <div class="field">
    <%= f.label :结束时间 %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :地址 %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :主办方 %><br />
    <%= f.text_field :organizer %>
  </div>
  <div class="field">
    <%= f.label :发起人 %><br />
    <%= f.text_field :sponsor %>
  </div>
  <div class="field">
    <%= f.label :联系方式 %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.kindeditor :content %>
  </div>
  <div class="field">
    <%= f.label :展示在主页 %><br />
    <%= f.check_box :is_index %>
  </div>
  <div class="actions">
    <%= f.submit "发布"%>
  </div>
<% end %>

app/views/events/_head_body.html.erb
<div class="head_body">
  <p class="main_title">
    活动中心
  </p>
  <div class="web_map">
    <%= link_to "首页", root_path %>
    <span class="map_go">>></span>
    <%= link_to "活动中心", events_path %>
    <% if admin_signed_in? %>
      (<span class="load"><%= link_to '新增活动', new_event_path %></span>)
    <% end %>
    <span class="map_go">>></span>
    <% if params[:controller] == 'events' and params[:action] == 'index' %>
      <%= link_to "全部", events_path %>      
    <% elsif params[:controller] == 'events' and params[:action] == 'show_area' and params[:area] == '社联活动' %>
      <%= link_to "社联活动", events_area_path('社联活动') %>
    <% elsif params[:controller] == 'events' and params[:action] == 'show_area' and params[:area] == '校园活动' %>
      <%= link_to "校园活动", events_area_path('校园活动') %>
    <% elsif params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '讲座沙龙' %>
      <%= link_to "讲座沙龙", events_kind_path('讲座沙龙') %>
    <% elsif params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '校园文化' %>
      <%= link_to "校园文化", events_kind_path('校园文化') %>
    <% elsif params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '竞赛创新' %>
      <%= link_to "竞赛创新", events_kind_path('竞赛创新') %>
    <% elsif params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '实践公益' %>
      <%= link_to "实践公益", events_kind_path('实践公益') %>
    <% elsif params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '其他' %>
      <%= link_to "其他", events_kind_path('其他') %>
    <% end %>
  </div>
</div>

app/views/events/_left_menu.html.erb
<div class="left_menu">
  <ul>
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'index' %>">
      <%= link_to "全部", events_path %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '讲座沙龙' %>">
      <%= link_to "讲座沙龙", events_kind_path('讲座沙龙') %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '校园文化' %>">
      <%= link_to "校园文化", events_kind_path('校园文化') %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '竞赛创新' %>">
      <%= link_to "竞赛创新", events_kind_path('竞赛创新') %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '实践公益' %>">
      <%= link_to "实践公益", events_kind_path('实践公益') %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'show_kind' and params[:kind] == '其他' %>">
      <%= link_to "其他", events_kind_path('其他') %>
    </li>
  </ul>
</div>

app/views/events/_right_body.html.erb
<% @top_events = Event.order("views_count DESC").limit(5) %>
<div class="right_body">
  <ul class="menu">
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'show_area' and params[:area] == '社联活动' %>">
      <a href="/events/area/社联活动">
        <span class="font_row">&lt;</span>
        社联活动
      </a>
    </li>
    <li class="<%= 'active' if params[:controller] == 'events' and params[:action] == 'show_area' and params[:area] == '校园活动' %>">
      <a href="/events/area/校园活动">
        <span class="font_row">&lt;</span>
        校园活动
      </a>
    </li>
  </ul>
  <div class="text_box">
    <p class="text_title">热门活动</p>
    <ul class="text_content">
      <% @top_events.each do |top_event| %>
      <li>
        <%= link_to top_event.title, top_event %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/events/edit.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<div id="body">
  <div class="inner_body">
		<%= link_to '返回', :back %>
		<%= link_to '查看', @event %>

		<h2>修改"<%= @event.title %>"</h2>
		
		<%= render 'form' %>

  </div>
</div>

app/views/events/index.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "activity_list", :media => "all" %>
<% provide :title, "活动中心" %>
<div id="body">
  <div class="inner_body">
    <%= render 'head_body' %>
    <div class="left_body" style="padding-left:0px;">
      <div class="content">
        <%= render 'left_menu' %>
        <div class="right_content">
          <% @events.each do |event| %>
            <div class="activity_box">
              <div class="pic_box">
                <% if event.photo? %>
                  <%= image_tag event.photo.url(:event), :width => "150px", :height => "100px" %>
                <% else %>
                  <%= image_tag "event_default.jpg", :width => "150px", :height => "100px" %>
                <% end %>
              </div>
              <div class="pic_info">
                <p class="the_title">
                  <%= link_to event.title, event %>
                </p>
                <p class="the_item">
                  <%= event.begin.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="the_item">
                  <%= event.end.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="the_item">
                  地址：<%= event.address %>
                </p>
                <p class="the_item">
                  主办方：<%= event.organizer %>
                </p>
                <div class="time_die">
                  <% @surplus = event.end - Time.now %>
                  <% if @surplus >= 0 %>
                    <% surplus = @surplus/86400 %>
                    <span class="activity_time">剩余约<%= surplus.to_i %>天</span>
                    <%= image_tag "label.jpg" %>
                  <% else %>
                    <span class="activity_time  die_date">已结束</span>
                    <%= image_tag "label_die.jpg" %>
                  <% end %>
                </div>
              </div>
              <div class="Clear"></div>
            </div>
          <% end %>
          <div class="page_box">
            <%= paginate @events %>
          </div>
        </div>
        <div class="Clear"></div>
      </div>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>

app/views/events/new.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<div id="body">
  <div class="inner_body">
		<%= link_to '返回', events_path %>

		<h2>新增活动</h2>

		<%= render 'form' %>

  </div>
</div>

app/views/events/show.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "an_activity", :media => "all" %>
<% provide :title, "活动中心 | "+@event.title %>
<div id="body">
  <div class="inner_body">
    <div class="head_body">
      <p class="main_title">
        活动中心
      </p>
      <div class="web_map">
        <%= link_to "首页", root_path %>
        <span class="map_go">>></span>
        <%= link_to "活动中心", events_path %>
        <span class="map_go">>></span>
          <%= @event.title %>
          <% if admin_signed_in? %>
            (<span class="load"><%= link_to '修改', edit_event_path %></span>)
          <% end %>
      </div>
    </div>
    <div class="left_body">
      <div class="content">
        <div class="star_list">
            <div class="small_title">
              <%= @event.title %>
            </div>
            <div class="pic_module">
              <div class="pic_box">
                <% if @event.photo? %>
                  <%= image_tag @event.photo.url(:intro), :style => "width:220px;height:153px" %>
                <% else %>
                  <%= image_tag "event_default.jpg", :height => "154px" %>
                <% end %>
              </div>
              <div class="pic_info">
                <p class="module_item">
                  开始时间：<%= @event.begin.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="module_item">
                  截止时间：<%= @event.end.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="module_item">
                  地点：<%= @event.address %>
                </p>
                <p class="module_item">
                  主办方：<%= @event.organizer %>
                </p>
                <p class="module_item">
                  发起人：<%= @event.sponsor %>
                </p>
                <p class="module_item">
                  联系方式：<%= @event.contact %>
                </p>
                <p class="module_item">
                  发起时间：<%= @event.created_at.strftime("%Y年%m月%d日") %>
                </p>
                <div class="date_label">
                  <% @surplus = @event.end - Time.now %>
                  <% if @surplus >= 0 %>
                    <% surplus = @surplus/86400 %>
                    <%= image_tag "label.jpg" %>
                    <span class="date">剩余约<%= surplus.to_i %>天</span>
                  <% else %>
                    <%= image_tag "label_die.jpg" %>
                    <span class="date">已结束</span>
                  <% end %>
                </div>
              </div>
              <div class="Clear"></div>
            </div>
            <div class="small_title">
              活动介绍
            </div>
          <div class="text_module">
            <%= raw @event.content %>
          </div>
        </div>
        <%= render 'shares/baidu_share' %>
      </div>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>

app/views/events/show_area.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "activity_list", :media => "all" %>
<% provide :title, "活动中心" %>
<div id="body">
  <div class="inner_body">
    <%= render 'head_body' %>
    <div class="left_body" style="padding-left:0px;">
      <div class="content">
        <%= render 'left_menu' %>
        <div class="right_content">
          <% @event_areas.each do |event| %>
            <div class="activity_box">
              <div class="pic_box">
                <% if event.photo? %>
                  <%= image_tag event.photo.url(:event), :width => "150px", :height => "100px" %>
                <% else %>
                  <%= image_tag "event_default.jpg", :width => "150px", :height => "100px" %>
                <% end %>
              </div>
              <div class="pic_info">
                <p class="the_title">
                  <%= link_to event.title, event %>
                </p>
                <p class="the_item">
                  <%= event.begin.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="the_item">
                  <%= event.end.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="the_item">
                  <%= event.address %>
                </p>
                <p class="the_item">
                  主办方：<%= event.organizer %>
                </p>
                <div class="time_die">
                  <% @surplus = event.end - Time.now %>
                  <% if @surplus >= 0 %>
                    <% surplus = @surplus/86400 %>
                    <span class="activity_time">剩余约<%= surplus.to_i %>天</span>
                    <%= image_tag "label.jpg" %>
                  <% else %>
                    <span class="activity_time  die_date">已结束</span>
                    <%= image_tag "label_die.jpg" %>
                  <% end %>
                </div>
              </div>
              <div class="Clear"></div>
            </div>
          <% end %>
          <div class="page_box">
            <%= paginate @event_areas %>
          </div>
        </div>
        <div class="Clear"></div>
      </div>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>

app/views/events/show_kind.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "activity_list", :media => "all" %>
<% provide :title, "活动中心" %>
<div id="body">
  <div class="inner_body">
    <%= render 'head_body' %>
    <div class="left_body" style="padding-left:0px;">
      <div class="content">
        <%= render 'left_menu' %>
        <div class="right_content">
          <% @event_kinds.each do |event| %>
            <div class="activity_box">
              <div class="pic_box">
                <% if event.photo? %>
                  <%= image_tag event.photo.url(:event), :width => "150px", :height => "100px" %>
                <% else %>
                  <%= image_tag "event_default.jpg", :width => "150px", :height => "100px" %>
                <% end %>
              </div>
              <div class="pic_info">
                <p class="the_title">
                  <%= link_to event.title, event %>
                </p>
                <p class="the_item">
                  <%= event.begin.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="the_item">
                  <%= event.end.strftime("%Y年%m月%d日 %H:%M") %>
                </p>
                <p class="the_item">
                  <%= event.address %>
                </p>
                <p class="the_item">
                  主办方：<%= event.organizer %>
                </p>
                <div class="time_die">
                  <% @surplus = event.end - Time.now %>
                  <% if @surplus >= 0 %>
                    <% surplus = @surplus/86400 %>
                    <span class="activity_time">剩余约<%= surplus.to_i %>天</span>
                    <%= image_tag "label.jpg" %>
                  <% else %>
                    <span class="activity_time  die_date">已结束</span>
                    <%= image_tag "label_die.jpg" %>
                  <% end %>
                </div>
              </div>
              <div class="Clear"></div>
            </div>
          <% end %>
          <div class="page_box">
            <%= paginate @event_kinds %>
          </div>
        </div>
        <div class="Clear"></div>
      </div>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>