config/routes.rb
Houtai::Application.routes.draw do
  resources :links

  resources :videos

  resources :articles

  resources :notices

  resources :periodicals

  match '/downloads/kind/:kind', to: 'downloads#show_kind', :as => 'downloads_kind'

  resources :downloads

  resources :albums do
    resources :photos
  end

  match '/aboutshetuans/kind/:kind', to: 'aboutshetuans#show_kind', :as => 'aboutshetuans_kind'

  match '/aboutshetuans/star', to: 'aboutshetuans#star'

  resources :aboutshetuans

  resources :stars

  match '/aboutshelians/theme/:theme', to: 'aboutshelians#theme', :as => 'aboutshelians_theme'

  match '/aboutshelians/star', to: 'aboutshelians#star'

  resources :aboutshelians

  mount Rich::Engine => '/rich', :as => 'rich'
  
  match '/events/area/:area', to: 'events#show_area', :as => 'events_area'

  match '/events/kind/:kind', to: 'events#show_kind', :as => 'events_kind'

  resources :events

  root :to => 'home#index'

  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'
  
  devise_for :admins

end

app/models/aboutshelian.rb
#coding: utf-8
class Aboutshelian < ActiveRecord::Base
	attr_accessible :title, :content

	validates_presence_of :title, :content

	def title_enum
		['社联章程','社联骨干','工作流程','主席团','秘书处','督导处','外联部','内务部','宣传部','策划部','新闻部']
	end

end

app/models/aboutshetuan.rb
#coding: utf-8
class Aboutshetuan < ActiveRecord::Base
	attr_accessible :name, :president, :contact, :kind, :institute, :begin, :is_excellent, :detail, :logo
	
	validates_presence_of :name, :president, :kind, :begin
	validates_uniqueness_of :name
	# has_many :attachments, :as => :attachmentable, :dependent => :destroy

  mount_uploader :logo, AttachmentUploader

	def kind_enum
		['社会公益类','体育运动类','文艺特长类','学术创新类','应用实践类']
	end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/album.rb
class Album < ActiveRecord::Base
	attr_accessible :name, :description
	
	has_many :photos, :dependent => :destroy
	
	validates_presence_of :name
	
	validates_uniqueness_of :name

  paginates_per 12

	default_scope order: 'albums.created_at DESC'

	def at_least_one_photo?
		delf.photos.present?
	end
end

app/models/article.rb
class Article < ActiveRecord::Base
	attr_accessible :title, :author, :unit, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'articles.created_at DESC'
end

app/models/download.rb
#coding: utf-8
class Download < ActiveRecord::Base
	attr_accessible :description, :kind, :attachment
	
	validates_presence_of :description, :kind, :attachment
	validates_uniqueness_of :attachment

  mount_uploader :attachment, AttachmentUploader

	def kind_enum
		['成立社团相关','社团事务相关','场地借用相关']
	end
end

app/models/event.rb
#coding: utf-8
class Event < ActiveRecord::Base
	attr_accessible :title, :kind, :photo, :begin, :end, :address, :organizer, :sponsor, :area, :views_count, :contact, :is_index, :content
	
	validates_presence_of :title, :kind, :begin, :end, :address, :organizer, :content, :area

  mount_uploader :photo, AttachmentUploader
	
	acts_as_views_count :delay => 1
	# default_scope order: 'events.created_at DESC'
	
	def kind_enum
		['讲座沙龙','校园文化','竞赛创新','实践公益','其他']
	end
	def area_enum
		['社联活动','校园活动']
	end
end

app/models/link.rb
class Link < ActiveRecord::Base
	attr_accessible :name, :address
	validates_presence_of :name, :address
	validates_uniqueness_of :name, :address
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	attr_accessible :title, :from, :content, :views_count
	
	validates_presence_of :title, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'notices.created_at DESC'
end

app/models/periodical.rb
class Periodical < ActiveRecord::Base
	attr_accessible :name, :author, :unit, :content, :views_count
	
	validates_presence_of :name, :content

	acts_as_views_count :delay => 1
	# default_scope order: 'periodicals.created_at DESC'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessible :photo_file, :album_id, :description

	validates_presence_of :album_id, :photo_file

  belongs_to :album
  
  mount_uploader :photo_file, AttachmentUploader

  paginates_per 35
end

app/models/star.rb
#coding: utf-8
class Star < ActiveRecord::Base
	attr_accessible :name, :photo, :department, :position, :contact, :institute, :motto, :detail, :area
	
	validates_presence_of :name, :department, :area
	validates_uniqueness_of :name

  mount_uploader :photo, AttachmentUploader
  
  paginates_per 1

	def area_enum
		['社联之星','社团之星']
	end
end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :name, :video_id, :screenshot, :views_count
  
	validates_presence_of :name, :video_id, :screenshot

  mount_uploader :screenshot, AttachmentUploader
	
	acts_as_views_count :delay => 1

	default_scope order: 'videos.created_at DESC'

  paginates_per 12
end

app/controllers/aboutshetuans_controller.rb
#coding: utf-8
class AboutshetuansController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  # GET /aboutshetuans
  # GET /aboutshetuans.json
  def index
    @aboutshetuans = Aboutshetuan.order("created_at desc").page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aboutshetuans }
    end
  end

  # GET /aboutshetuans/1
  # GET /aboutshetuans/1.json
  def show
    @aboutshetuan = Aboutshetuan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aboutshetuan }
    end
  end

  def show_kind
    @aboutshetuan_kinds =  Aboutshetuan.where(:kind => params[:kind]).page params[:page]
  end

  def star
    @stars = Star.where(:area => '社团之星').page params[:page]
  end

  # GET /aboutshetuans/new
  # GET /aboutshetuans/new.json
  def new
    @aboutshetuan = Aboutshetuan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aboutshetuan }
    end
  end

  # GET /aboutshetuans/1/edit
  def edit
    @aboutshetuan = Aboutshetuan.find(params[:id])
  end

  # POST /aboutshetuans
  # POST /aboutshetuans.json
  def create
    @aboutshetuan = Aboutshetuan.new(params[:aboutshetuan])

    respond_to do |format|
      if @aboutshetuan.save
        format.html { redirect_to @aboutshetuan, notice: 'Aboutshetuan was successfully created.' }
        format.json { render json: @aboutshetuan, status: :created, location: @aboutshetuan }
      else
        format.html { render action: "new" }
        format.json { render json: @aboutshetuan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aboutshetuans/1
  # PUT /aboutshetuans/1.json
  def update
    @aboutshetuan = Aboutshetuan.find(params[:id])

    respond_to do |format|
      if @aboutshetuan.update_attributes(params[:aboutshetuan])
        Attachment.create(:attachment => params[:attachment], :attachmentable => @aboutshetuan) if params[:attachment]
        format.html { redirect_to @aboutshetuan, notice: 'Aboutshetuan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aboutshetuan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutshetuans/1
  # DELETE /aboutshetuans/1.json
  def destroy
    @aboutshetuan = Aboutshetuan.find(params[:id])
    @aboutshetuan.destroy

    respond_to do |format|
      format.html { redirect_to aboutshetuans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aboutshetuans_helper.rb
module AboutshetuansHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def no_album?
      !Album.first
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/aboutshetuans/_form.html.erb
<%= form_for(@aboutshetuan, :html => {:multipart => true}) do |f| %>
  <% if @aboutshetuan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aboutshetuan.errors.count, "error") %> prohibited this aboutshetuan from being saved:</h2>

      <ul>
      <% @aboutshetuan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :社团照片 %><br />
    <%= f.file_field :logo %><br />
  </div>
  <div class="field">
    <%= f.label :名称 %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :社长 %><br />
    <%= f.text_field :president %>
  </div>
  <div class="field">
    <%= f.label :联系方式 %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :类型 %><br />
    <%= f.select :kind, ['社会公益类','体育运动类','文艺特长类','学术创新类','应用实践类'] %>
  </div>
  <div class="field">
    <%= f.label :所属学院 %><br />
    <%= f.text_field :institute %>
  </div>
  <div class="field">
    <%= f.label :成立时间 %><br />
    <%= f.datetime_select :begin, :start_year => 1956 %>
  </div>
  <div class="field">
    <%= f.label :详细介绍 %><br />
    <%= f.kindeditor :detail %>
  </div>
  <div class="field">
    <%= f.label :设为优秀社团 %><br />
    <%= f.check_box :is_excellent %>
  </div>
  <div class="actions">
    <%= f.submit "发布"%>
  </div>
<% end %>

app/views/aboutshetuans/_head_body.html.erb
<div class="head_body">
  <p class="main_title">
    关于社团
  </p>
  <div class="web_map">
    <%= link_to "首页", root_path %>
    <span class="map_go">>></span>
    <%= link_to "关于社团", aboutshetuans_path %>
      <% if admin_signed_in? %>
        (<span class="load"><%= link_to '添加社团', new_aboutshetuan_path %></span>)
      <% end %>
    <span class="map_go">>></span>
    <% if params[:controller] == 'aboutshetuans' and params[:action] == 'index' %>
      社团列表
      <span class="map_go">>></span>
      全部
    <% elsif params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '社会公益类' %>
      社团列表
      <span class="map_go">>></span>
      社会公益类
    <% elsif params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '体育运动类' %>
      社团列表
      <span class="map_go">>></span>
      体育运动类
    <% elsif params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '文艺特长类' %>
      社团列表
      <span class="map_go">>></span>
      文艺特长类
    <% elsif params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '学术创新类' %>
      社团列表
      <span class="map_go">>></span>
      学术创新类
    <% elsif params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '应用实践类' %>
      社团列表
      <span class="map_go">>></span>
      应用实践类
    <% end %>
  </div>
</div>

app/views/aboutshetuans/_right_body.html.erb
<% @excellent_shetuans = Aboutshetuan.where(:is_excellent => '1') %>
<div class="right_body">
  <ul class="menu">
    <li class="tree_root">
      <a href="/aboutshetuans">
        <span class="font_row">&lt;</span>
        社团列表
      </a>
      <ul class="tree_menu">
        <li class="<%= 'active' if params[:controller] == 'aboutshetuans' and params[:action] == 'index' %>">
          <a href="/aboutshetuans">
            <span class="font_row">&lt;</span>
            全部
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '社会公益类' %>">
          <a href="/aboutshetuans/kind/社会公益类">
            <span class="font_row">&lt;</span>  
            社会公益类
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '体育运动类' %>">
          <a href="/aboutshetuans/kind/体育运动类">
            <span class="font_row">&lt;</span>
            体育运动类
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '文艺特长类' %>">
          <a href="/aboutshetuans/kind/文艺特长类">
            <span class="font_row">&lt;</span>
            文艺特长类
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'aboutshetuans' and params[:action] == 'show_kind' and params[:kind] == '应用实践类' %>">
          <a href="/aboutshetuans/kind/应用实践类">
            <span class="font_row">&lt;</span>
            应用实践类
          </a>
        </li>
      </ul>
    </li>
    <li class="<%= 'active' if params[:controller] == 'aboutshetuans' and params[:action] == 'star' %>">
      <%= link_to "社团之星", aboutshetuans_star_path %>
    </li>
    <li class="tree_root">
      <a>
        优秀社团
      </a>
      <ul class="tree_menu">
        <% @excellent_shetuans.each do |shetuan| %>
        <li>
          <%= link_to shetuan.name, shetuan %>
        </li>
        <% end %>
      </ul>
    </li>
  </ul>
</div>

app/views/aboutshetuans/edit.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<div id="body">
  <div class="inner_body">
		<%= link_to '返回', :back %>
		<%= link_to '查看', @aboutshetuan %>

		<h2>修改"<%= @aboutshetuan.name %>"</h2>

		<%= render 'form' %>

  </div>
</div>

app/views/aboutshetuans/index.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "league_list", :media => "all" %>
<style type="text/css">
  .pic_info{
    width:60%!important;
  }
  .pic_box{
    width: 40%!important;
  }
</style>
<% provide :title, "关于社团" %>
<div id="body">
  <div class="inner_body">
    <%= render 'head_body' %>
    <div class="left_body">
      <div class="content">
        <ul class="league_lists">
          <% @aboutshetuans.each do |shetuan| %>
          <li>
            <div class="pic_module">
              <div class="pic_box">
                <% if shetuan.logo? %>
                  <%= image_tag shetuan.logo.url(:shetuan_logo), :width => "100px", :height => "100px" %>
                <% else %>
                  <%= image_tag "shetuan_default.jpg", :width => "100px", :height => "100px" %>
                <% end %>
              </div>
              <div class="pic_info">
                <p class="the_title">
                  <%= link_to shetuan.name, shetuan %>
                </p>
                <p class="module_item">
                  社长：<%= shetuan.president %>
                </p>
                <p class="module_item">
                  类型：<%= shetuan.kind %>
                </p>
                <p class="module_item">
                  成立时间：<%= shetuan.begin.strftime("%Y年") if shetuan.begin? %>
                </p>
              </div>
            </div>
          </li>
          <% end %>
          <div class="Clear"></div>
          <div class="page_box">
            <%= paginate @aboutshetuans %>
          </div>
        </ul>
        <div class="Clear"></div>
      </div>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>

app/views/aboutshetuans/new.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<div id="body">
  <div class="inner_body">
		<%= link_to '返回', aboutshetuans_path %>

		<h2>添加社团</h2>

		<%= render 'form' %>

  </div>
</div>

app/views/aboutshetuans/show.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "about_league", :media => "all" %>
<style type="text/css">
  .text_module p{
    font-size: 14px;
    line-height: 2.0em;
  }
  .text_module{
    margin-right: 20px;
  }
</style>
<% provide :title, "关于社团 | "+@aboutshetuan.name %>
<div id="body">
  <div class="inner_body">
    <div class="head_body">
      <p class="main_title">
        关于社团
      </p>
      <div class="web_map">
        <%= link_to "首页", root_path %>
        <span class="map_go">>></span>
        <%= link_to "关于社团", aboutshetuans_path %>
        <span class="map_go">>></span>
        <%= @aboutshetuan.name %>
        <% if admin_signed_in? %>
          (<span class="load"><%= link_to '修改', edit_aboutshetuan_path %></span>)
        <% end %>
      </div>
    </div>
    <div class="left_body">
      <div class="content">
        <ul class="star_list">
          <li>
            <div class="pic_module">
              <div class="pic_box">
                <% if @aboutshetuan.logo? %>
                  <%= image_tag @aboutshetuan.logo.url(:shetuan_logo), :width => "140px", :height => "140px" %>
                <% else %>
                  <%= image_tag "shetuan_default.jpg", :width => "140px", :height => "140px" %>
                <% end %>
              </div>
              <div class="pic_info">
                <p class="module_title">
                  <%= @aboutshetuan.name %>
                </p>
                <p class="module_item">
                  社长：<%= @aboutshetuan.president %>
                </p>
                <p class="module_item">
                  联系方式：<%= @aboutshetuan.contact %>
                </p>
                <p class="module_item">
                  类型：<%= @aboutshetuan.kind %>
                </p>
                <p class="module_item">
                  挂靠学院：<%= @aboutshetuan.institute %>
                </p>
                <p class="module_item">
                  成立时间：<%= @aboutshetuan.begin.strftime("%Y年") if @aboutshetuan.begin? %>
                </p>
              </div>
              <div class="Clear"></div>
            </div>
            <div class="small_title">
              简介：
            </div>
            <div class="text_module">
              <%= raw @aboutshetuan.detail %>
            </div>
          </li>
        </ul>
      </div>
      <% @rencent_evnets = Event.order("created_at desc").where(:organizer => @aboutshetuan.name).limit(4) %>
      <% if !@rencent_evnets.empty? %>
        <div class="recent_activity">
          <ul>
            <li class="small_item_name">
              近期活动
            </li>
            <% @rencent_evnets.each do |event| %>
            <li>
              <% if event.photo? %>
                <%= link_to image_tag(event.photo.url(:event), :style => "width:150px;height:100px"), event %>
              <% else %>
                <%= link_to image_tag("event_default.jpg", :height => "154px"), event %>
              <% end %>
              <div class="name_bg"></div>
              <div class="activity_name"><%= event.title %></div>
            </li>
            <% end %>
          </ul>
          <div class="Clear"></div>
        </div>
      <% end %>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>

app/views/aboutshetuans/show_kind.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<%= stylesheet_link_tag  "league_list", :media => "all" %>
<style type="text/css">
  .pic_info{
    width:60%!important;
  }
  .pic_box{
    width: 40%!important;
  }
</style>
<% provide :title, "关于社团" %>
<div id="body">
  <div class="inner_body">
    <%= render 'head_body' %>
    <div class="left_body">
      <div class="content">
        <ul class="league_lists">
          <% @aboutshetuan_kinds.each do |shetuan| %>
          <li>
            <div class="pic_module">
              <div class="pic_box">
                <% if shetuan.logo? %>
                  <%= image_tag shetuan.logo.url(:shetuan_logo), :width => "100px", :height => "100px" %>
                <% else %>
                  <%= image_tag "shetuan_default.jpg", :width => "100px", :height => "100px" %>
                <% end %>
              </div>
              <div class="pic_info">
                <p class="the_title">
                  <%= link_to shetuan.name, shetuan %>
                </p>
                <p class="module_item">
                  社长：<%= shetuan.president %>
                </p>
                <p class="module_item">
                  类型：<%= shetuan.kind %>
                </p>
                <p class="module_item">
                  成立时间：<%= shetuan.begin.strftime("%Y年") if shetuan.begin? %>
                </p>
              </div>
            </div>
          </li>
          <% end %>
          <div class="Clear"></div>
          <div class="page_box">
            <%= paginate @aboutshetuan_kinds %>
          </div>
        </ul>
        <div class="Clear"></div>
      </div>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>

app/views/aboutshetuans/star.html.erb
<%= stylesheet_link_tag  "model", :media => "all" %>
<%= stylesheet_link_tag  "model_1", :media => "all" %>
<% provide :title, "关于社联 | 社联之星" %>
<style type="text/css">
    .pic_info{
        margin-left: 10px;
    }
</style>
<div id="body">
  <div class="inner_body">
    <div class="head_body">
      <p class="main_title">
        关于社团
      </p>
      <div class="web_map">
        <%= link_to "首页", root_path %>
        <span class="map_go">>></span>
        <%= link_to "关于社团", aboutshetuans_path %>
        <span class="map_go">>></span>
          社团之星
          <% if admin_signed_in? %>
            (<span class="load"><%= link_to '新增社团之星', new_star_path %></span>)
          <% end %>
      </div>
    </div>
    <div class="left_body">
      <div class="content">
        <ul class="star_list">
          <% @stars.each do |star| %>
          <li>
            <div class="small_title">
              <%= star.name %>
              <% if admin_signed_in? %>
                (<span class="load"><%= link_to '修改', edit_star_path(star) %></span>)
              <% end %>
            </div>
            <div class="pic_module">
              <div class="pic_box">
                <%= image_tag star.photo.url(:intro), :width => "200px", :height => "140px" if star.photo? %>
              </div>
              <div class="pic_info">
                <p class="module_item">
                  姓名：<%= star.name %>
                </p>
                <p class="module_item">
                  部门：<%= star.department %>
                </p>
                <p class="module_item">
                  职位：<%= star.position %>
                </p>
                <p class="module_item">
                  联系方式：<%= star.contact %>
                </p>
                <p class="module_item">
                  学院：<%= star.institute %>
                </p>
                <p class="module_item">
                  个性签名：<%= star.motto %>
                </p>
              </div>
              <div class="Clear"></div>
            </div>
            <div class="small_title">
              个人简介：
            </div>
            <div class="text_module">
              <%= raw star.detail %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="page_box">
        <%= paginate @stars %>
      </div>
    </div>
    <%= render 'right_body' %>
    <div class="Clear"></div>
  </div>
</div>